name: TheDeadlyMouse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10327
title: TDM Gaming
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf21f'
    - '#3b51d6'
    - '#ea1919'
    - '#000000'
    - '#a1ae6b'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 1
purpose:
  - name: follow
    item: 0658f657-2269-45e9-8b49-3c558c414058
    url: null
