name: TheDeadlyMouse
favicon: null
layout_spectrum: 0.33115
title: TDM Gaming
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c01d2e'
    - '#fefefe'
    - '#000000'
    - '#f7c8cf'
    - '#79797b'
  brandStrength: 0.375
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: 'null'
    url: null
