name: TheDeadlyMouse
favicon: null
layout_spectrum: 0.50328
title: TDM Gaming
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c01d2e'
    - '#fefefe'
    - '#000000'
    - '#f7c8cf'
    - '#79797b'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: 0658f657-2269-45e9-8b49-3c558c414058
    url: null
