name: TheDeadlyMouse
favicon: null
layout_spectrum: 0.89508
title: TDM Gaming
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212121'
    - '#474747'
    - '#cacaca'
    - '#8a8a8a'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: null
    url: null
