name: TheDeadlyMouse
favicon: null
layout_spectrum: 0.33115
title: TDM Gaming
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c01d2e'
    - '#fefefe'
    - '#000000'
    - '#f7c8cf'
    - '#79797b'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: 7e22d1ab-a67c-46a0-8261-41d8e3284ceb
    url: null
